import type { Locale } from "@/lib/i18n";

export const retailFlowCopy = {
	en: {
		label: "Interactive retail platform",
		caption: "Follow one POS or kiosk sale through your system.",
		store: "Store / 01",
		receipt: "Checkout begins.",
		order: "Order #0042",
		item: "Everyday essentials",
		quantity: "3 items · 1 connected journey",
		saved: "Saved on device",
		complete: "Sale synchronized",
		sending: "Sending saved sale",
		queued: "Waiting to sync",
		steps: [
			{ title: "Payment / credit", detail: "Terms confirmed" },
			{ title: "Inventory / ERP", detail: "Stock updated" },
			{ title: "Fulfillment", detail: "Order received" },
			{ title: "Control center", detail: "Sale visible" },
		],
		connected: "Every part, in sync.",
		offline:
			"Connection lost. The sale is saved on the device; connected systems wait.",
		syncing:
			"Connection restored. The saved sale is moving through the system.",
		recovered: "Back in sync. One saved sale, delivered to every system.",
		tryOutage: "Try an outage",
		restore: "Restore connection",
		restoring: "Synchronizing…",
		noScript: "Enable JavaScript to try the outage example.",
	},
	fa: {
		label: "پلتفرم تعاملی خرده‌فروشی",
		caption: "مسیر یک فروش POS یا کیوسک را در سیستم خود دنبال کنید.",
		store: "فروشگاه / ۰۱",
		receipt: "شروع پرداخت.",
		order: "سفارش شماره ۰۰۴۲",
		item: "کالاهای روزمره",
		quantity: "۳ کالا · یک مسیر متصل",
		saved: "ذخیره روی دستگاه",
		complete: "فروش همگام شد",
		sending: "ارسال فروش ذخیره‌شده",
		queued: "در انتظار همگام‌سازی",
		steps: [
			{ title: "پرداخت / اعتبار", detail: "شرایط تأیید شد" },
			{ title: "موجودی / ERP", detail: "موجودی به‌روز شد" },
			{ title: "تکمیل سفارش", detail: "سفارش دریافت شد" },
			{ title: "مرکز کنترل", detail: "فروش قابل مشاهده است" },
		],
		connected: "همه‌چیز، هماهنگ با هم.",
		offline:
			"ارتباط قطع شد. فروش روی دستگاه ذخیره شده و سیستم‌های متصل منتظر می‌مانند.",
		syncing: "ارتباط برقرار شد. فروش ذخیره‌شده در مسیر همگام‌سازی با سیستم‌هاست.",
		recovered: "دوباره هماهنگ شدیم. یک فروش ذخیره‌شده، در تمام سیستم‌ها ثبت شد.",
		tryOutage: "قطعی را امتحان کنید",
		restore: "برقراری دوباره ارتباط",
		restoring: "در حال همگام‌سازی…",
		noScript: "برای امتحان نمونه قطعی، جاوااسکریپت را فعال کنید.",
	},
} satisfies Record<Locale, unknown>;
